### ISSUE TITLE
Very slow processing script on Nird

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/data_processing_scripts#13]
I tried to start a CAM processing script last Wednesday. After some time, the script just stopped without any progress and remained at that point until I killed the job yesterday.

As the original purpose of the script was to concatenate the ice output data, I tried to run the script on the ice model output on a case today.  After one hour the script has not completed a single file. Command and log below

(base) [oyvinds@login0-nird-lmd cases]$ /nird/home/goldy/Projects/data_processing_scripts/PostProc/rcat_noresm.sh --comp ice --keep-monthly /projects/NS9252K/noresm/cases/NSSP585frc2_f09_tn14_cloudxpice_220819 /nird/datalake/NS9252K/cases/NSSP585frc2_f09_tn14_cloudxpice_220819
====================
rcat_noresm.sh
====================
NorESM Case: /nird/projects/NS9252K/noresm/cases/NSSP585frc2_f09_tn14_cloudxpice_220819
Output Dir: /nird/datalake/NS9252K/cases/NSSP585frc2_f09_tn14_cloudxpice_220819
Compressing components: ice
Not moving any files
Merge files per year
Not merging monthly files into yearly files
Compression: 2
Threads: 4
Message Verbosity: Level 0
====================
--------------------
ice hist files: 32452
Cataloging history files for ice
31000 / 32452 files cataloged

**Comment by oyvindseland** [comment]
The ice option in script ran quite fast, it just took quite long time to summarize the files.
The processing of CAM files mentioned in the point above happened within the processing itself, not only for the preprocessing.
For KeyClim simulations I plan to use the script for all components except for atmosphere. Will just rsync the CAM output files

**Comment by gold2718** [comment]
I guess I'm confused because your example command does not include any CAM processing, only `--comp ice`. Was there a similar call for CAM?

**Comment by oyvindseland** [comment]
There was a similar call for CAM. At any rate the script worked better (and finished) for a similar case today, so it was a nird issue.
